- .github/workflows/staging.yml
chore: modify staging PR
test: service (#4)
* test: service
fix: test->ci
fix: staging.yml
fix: env file
fix: try 2
fix: build stage
test: add docker ps in ci command
test: fix docker-compose exec
test: try 3
chore: update packages
test: try 4
* fix: step on actions
> feat: add github actions

- .github/workflows/continuous_delivery.yml
- .github/workflows/continuous_integration.yml
- README.md
* test: try 1
* test: try 2
* test: try 3
* feat: add to cd too
> Feature/code climate (#18)

- .github/workflows/continuous_integration.yml
- README.md
> feat: add snyk on actions (#20)

- .eslintrc.js
- docker-compose.yml
- makefile
- package-lock.json
- package.json
- src/@types/environment.d.ts
- src/core/config/cache.ts
- src/core/config/enviroment_config.ts
- src/core/layers/providers.ts
- src/core/providers/mfa.repository.ts
- src/core/providers/mfa_code.repository.ts
- src/core/providers/user.repository.ts
- src/core/usecases/login.usecase.ts
- src/index.ts
- src/routes/mfa.route.ts
* feat: add snyk on actions (#20)
chore: add snyk badge
* chore: fix a lot of code smell and security issues (#23)
* chore: update readme (#22)
chore: update readme (#22)
chore: lint better (#25)
feat: env config fix (#26)
> Staging (#24)

- .github/workflows/continuous_integration.yml
- docker-compose.yml
- makefile
- package-lock.json
- package.json
- src/core/config/cache.ts
- src/core/config/database.ts
- src/index.ts
- test/integration/login.route.test.ts
- test/unit/providers/mfa_choose.repository.test.ts
- test/unit/usecases/login.usecase.test.ts
* chore: added integration test, not working
* feat: integration test
* fix: GH action with services
* test: try ci with make file
* test: make testi:ci
* fix: make test
* fix: two points
* test: try to fix exec
* fix: code climate
* test: try 2 to fix code climate
* fix: try 4 to fix code climate
> Feature/test providers (#28)

- README.md
- package-lock.json
- package.json
- src/@types/environment.d.ts
- src/core/config/enviroment_config.ts
- src/core/config/firebase.ts
- src/core/entities/mfa.ts
- src/core/entities/mfa_code.ts
- src/core/layers/README.md
- tsconfig.json
* feat: add firebase
* fix: md lint
> feat: add firebase (#36)

- .github/workflows/continuous_integration.yml
- package-lock.json
Proposal
Add Code climate Quality Gate
> feat: add code climate

- README.md
- src/config/kafka.ts
- src/core/providers/mfa_code.repository.ts
- src/core/usecases/driven/validating_code.driven.ts
- src/presentation/messaging/app.ts
- src/presentation/messaging/server.ts
- test/fixtures/user.ts
- test/integration/http/broker.route.test.ts
- test/integration/messaging/server.test.ts
- test/unit/providers/mfa_code.repository.test.ts
- test/unit/providers/organization.repository.test.ts
Proposal
- kakfka config to fix Topic creation
- fix kafka tests
> fix: kafka topcis and test

- src/core/layers/usecases.ts
- src/core/usecases/driver/list_mfa.driver.ts
- src/core/usecases/mfa.usecase.ts
- src/presentation/http/routes/mfa.route.ts
- test/integration/http/mfa.route.test.ts
- test/unit/usecases/mfa.usecase.test.ts
Proposal
- Add a new route to user see which MFA he has
> List MFA by User

- package-lock.json
- package.json
- src/config/metric.ts
- src/presentation/http/middlewares/metric.ts
- src/presentation/http/server.ts
**Proposal**
- Replace Prometheus lib for original
> chore: replace prometheus lib

- src/@types/express.d.ts
- src/config/kafka.ts
- src/presentation/http/middlewares/jwt.ts
**Proposal**
- Remove  any of the code
> feat: remove a lot of any

- package-lock.json
- package.json
- src/presentation/http/app.ts
- src/presentation/http/doc/swagger.json
- src/presentation/http/routes/user.route.ts
- test/integration/http/user.route.test.ts
- tsconfig.json
**Proposal**
- Add endpoint to swagger doc
> feat: add swagger

- src/core/usecases/token.usecase.ts
- src/presentation/http/middlewares/jwt.ts
- src/presentation/http/routes/organization.route.ts
**Proposal**
- Fix organization route adding /add
- remove consoler.error
- fix security issue removing headers
> feat: fix route, remove log, remove header

- src/core/entities/mfa.ts
- src/core/providers/mfa.repository.ts
- src/core/usecases/driver/create_mfa.driver.ts
- src/core/usecases/mfa.usecase.ts
**Proposal**
-fix return of secret when GA
> feat: now it's working for GA

- docker-compose.yml
- src/core/layers/usecases.ts
- src/core/providers/notification.provider.ts
- src/core/usecases/driven/creating_billing_user.driven.ts
- src/core/usecases/user.usecase.ts
- test/unit/usecases/user.usecase.test.ts
**Proposal**
- Add producer to topic USER_CREATED so billing can create on this side
> feat: add kafka to billing

- src/core/entities/user.ts
- src/core/providers/user.repository.ts
- src/core/usecases/driven/finding_user.driven.ts
- src/core/usecases/driver/list_user.driver.ts
- src/core/usecases/user.usecase.ts
- src/presentation/http/routes/user.route.ts
- test/integration/http/user.route.test.ts
**Proposal**
- Add a route for listing users
- Add integration test
> feat: add list all users

- src/config/logger.ts
**Proposal**
- leave console as main transport
> feat: same transport to all env

- db/migrations/20210526220337_create_user_table.sql
- db/migrations/20210527202631_create_mfa_table.sql
- db/migrations/20210703222838_create_admin.sql
- db/migrations/20211127225354_create_organization.sql
- db/migrations/20220109235424_create_user_info.sql
**Proposal**
- Formatter SQL files
**Links**
- https://www.dpriver.com/pp/sqlformat.htm
- https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools
> feat: lint sql files

- src/core/providers/notification.provider.ts
- src/core/usecases/driven/creating_system_user.driven.ts
- src/core/usecases/user.usecase.ts
- test/unit/usecases/user.usecase.test.ts
**Proposal**
- Change Billing to System name
> feat: change name

- .prettierignore
- src/core/config/cache.ts
- src/core/providers/organization.repository.ts
- src/core/usecases/driver/update_organization.driver.ts
- src/core/usecases/organization.usecase.ts
- src/presentation/http/doc/swagger.json
- src/presentation/http/routes/login.route.ts
- src/presentation/http/routes/logout.route.ts
- src/presentation/http/routes/mfa.route.ts
- src/presentation/http/routes/organization.route.ts
- src/presentation/http/routes/reset_password.route.ts
- src/presentation/http/routes/user.route.ts
- src/presentation/http/server.ts
- test/unit/providers/mfa_code.repository.test.ts
- test/unit/providers/notification.provider.test.ts
- test/unit/providers/organization.repository.test.ts
- test/unit/services/code.services.test.ts
- test/unit/usecases/logout.usecase.test.ts
- test/unit/usecases/mfa.usecase.test.ts
- test/unit/usecases/organization.usecase.test.ts
- test/unit/usecases/user.usecase.test.ts
**Proposal**
- FIx sonarcloud issues
> fix: routes and doc swagger
